import numpy as np
from pygame import *


ANCHO_CEL = 30
ALTO_CEL = 30
CANT_MINAS = 1
CANT_FIL = 8
CANT_COL = 8


ANCHO = CANT_COL*ANCHO_CEL
ALTO = CANT_FIL*ALTO_CEL
COLOR_BG = (80,80,80)
COLOR_PANEL = (50,60,50)
PANEL = ALTO//4
PANEL_RESTA =  ALTO - PANEL
PANEL_SUMA = ALTO + PANEL

GRIS = (40,40,40)
NEGRO = (50,12,12)
RESOLUCION = (ANCHO,PANEL_SUMA)

matriz = np.zeros((CANT_FIL+2,CANT_COL+2),dtype = int)

print(matriz)
print(PANEL)
